/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.Dialogs;

import Controllers.BookController;
import java.sql.Date;
import java.util.HashMap;

/**
 *
 * @author 2ndyrGroupC
 */
public class AddEditBook extends javax.swing.JDialog {

    /**
     * Creates new form AddBook
     */
    static HashMap<String, String> data = null;

    public AddEditBook(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public AddEditBook(java.awt.Frame parent, boolean modal, HashMap<String, String> data) {
        super(parent, modal);
        initComponents();
        this.SaveEditBook.setText("Edit");
        this.data = data;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Container1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BookTitleField = new javax.swing.JTextField();
        BookTitle = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BookAuthor = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BookGenreField = new javax.swing.JTextField();
        BookAuthorField = new javax.swing.JTextField();
        BookYearField = new javax.swing.JTextField();
        BockStockField = new javax.swing.JTextField();
        SaveEditBook = new javax.swing.JButton();
        CloseBookForm = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add New Book");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 267, 37, 268);
        jPanel1.add(jLabel1, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        Container1.setBackground(new java.awt.Color(102, 102, 102));
        Container1.setPreferredSize(new java.awt.Dimension(400, 400));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Please fill in the need information");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        BookTitleField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BookTitleField.setText("Book Title");

        BookTitle.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BookTitle.setForeground(new java.awt.Color(255, 255, 255));
        BookTitle.setText("Book Title: ");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Book Genre: ");
        jLabel4.setToolTipText("");

        BookAuthor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BookAuthor.setForeground(new java.awt.Color(255, 255, 255));
        BookAuthor.setText("Book Author");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Year Published");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Stock Number");

        BookGenreField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BookGenreField.setText("Book Genre");

        BookAuthorField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BookAuthorField.setText("Book Author");

        BookYearField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BookYearField.setText("Year Published");

        BockStockField.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BockStockField.setText("Stock Number");

        SaveEditBook.setBackground(new java.awt.Color(0, 51, 102));
        SaveEditBook.setForeground(new java.awt.Color(255, 255, 255));
        SaveEditBook.setText("Save");
        SaveEditBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveEditBookActionPerformed(evt);
            }
        });

        CloseBookForm.setBackground(new java.awt.Color(102, 0, 0));
        CloseBookForm.setForeground(new java.awt.Color(255, 255, 255));
        CloseBookForm.setText("Close");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Container1Layout = new javax.swing.GroupLayout(Container1);
        Container1.setLayout(Container1Layout);
        Container1Layout.setHorizontalGroup(
            Container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(Container1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(Container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BookTitle)
                    .addComponent(jLabel4)
                    .addComponent(BookAuthor)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(29, 29, 29)
                .addGroup(Container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Container1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(SaveEditBook)
                        .addGap(18, 18, 18)
                        .addComponent(CloseBookForm))
                    .addComponent(BockStockField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BookYearField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BookAuthorField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BookGenreField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BookTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Container1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(78, 78, 78))
        );
        Container1Layout.setVerticalGroup(
            Container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Container1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookTitleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(BookGenreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BookAuthor)
                    .addComponent(BookAuthorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(Container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(BookYearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(Container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BockStockField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Container1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CloseBookForm)
                    .addComponent(SaveEditBook))
                .addGap(29, 29, 29)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(Container1, new java.awt.GridBagConstraints());

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveEditBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveEditBookActionPerformed
        // TODO add your handling code here:

        String title = this.BookTitleField.getText();
        String author = this.BookAuthorField.getText();
        String genre = this.BookGenreField.getText();
        String year = this.BookYearField.getText();
        String stock = this.BockStockField.getText();
        if (BookController.validateAndBookInfo(author, genre, title, year, stock)) {
            Date yearPublished = Date.valueOf(year);
            int stockNumber = Integer.parseInt(stock);
            
            if (this.data != null) {
                int id = Integer.parseInt(data.get("id"));
                BookController.updateBook(id, author, genre, title, yearPublished, stockNumber);
                return;
            }
            BookController.addBook(author, genre, title, yearPublished, stockNumber);
        }
    }//GEN-LAST:event_SaveEditBookActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BockStockField;
    private javax.swing.JLabel BookAuthor;
    private javax.swing.JTextField BookAuthorField;
    private javax.swing.JTextField BookGenreField;
    private javax.swing.JLabel BookTitle;
    private javax.swing.JTextField BookTitleField;
    private javax.swing.JTextField BookYearField;
    private javax.swing.JButton CloseBookForm;
    private javax.swing.JPanel Container1;
    private javax.swing.JButton SaveEditBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
